site_name: 'راهنمای کامل توسعه هسته سیستم‌عامل اندروید'
site_description: 'همه چیز درباره کار با AOSP و برنامه‌نویسی و ایجاد تغییر در هسته سیستم‌عامل اندروید'
site_author: 'تیم سبا'
docs_dir: 'src'
site_dir: 'build/html'
extra_css:
  - assets/fastyle.css
theme:
  name: 'material'
  font: false
  language: 'fa'
  direction: 'rtl'
  logo:
    icon: 'smartphone'
  feature:
    tabs: true
nav:
  - آشنایی:
    - آیا اندروید متن باز است؟: 'introduction/is-android-open-source.md'
    - AOSP چیست: 'introduction/aosp.md'
    - اصطلاحات اندروید: 'introduction/glossary.md'
    - درباره راهنما: 'index.md'

    

  - مفاهیم:
      - انیمیشن راه‌اندازی: 'concepts/boot-animation.md'
      - امضای دیجیتالی: 'concepts/signing.md'


    


  - فرآیند ساخت:
    - پیش‌نیاز‌ها: 'build/requirement/index.md'
    - دریافت کد AOSP: 'build/aosp_code.md'
    - آشنایی با فرآیند ساخت: 'build/build.md'
    - اجرا روی شبیه‌ساز: 'build/emulator.md'
    - نصب: 'other/install/install.md'
    - مشکلات: 'build/problems/index.md'


  - تغییرات ساده:
    - افزودن برنامه پیش‌فرض: 'modifications/apk-bundling.md'

  - دستگاه‌ها:
    - ملاحظات انواع دستگاه‌ها: devices/intro.md
    - Tecno Camon C9: devices/tecno/c9.md


  - سایر منابع:
    - معرفی منابع: 'references/index.md'
    - کتاب‌ها: 'references/books.md'
