site_name: 'راهنمای کامل توسعه هسته سیستم‌عامل اندروید'
site_description: 'همه چیز درباره کار با AOSP و برنامه‌نویسی و ایجاد تغییر در هسته سیستم‌عامل اندروید'
site_author: 'تیم سبا'
docs_dir: 'src'
site_dir: 'build/html'
extra_css:
  - assets/fastyle.css
theme:
  name: 'material'
  font: false
  language: 'fa'
  direction: 'rtl'
  logo:
    icon: 'smartphone'
  feature:
    tabs: true
nav:
  - آشنایی و توضیحات:
      - سخن آغازین : 'introduction/start_page.md'
      - AOSP چیست: 'introduction/aosp.md'
      - مقالات :
          - آیا اندروید متن‌باز است؟  : 'introduction/is-android-open-source.md'
      - اخبار :
          - اخبار سیستم‌عامل : 'introduction/os_news.md'
          - شرکت‌های سازنده‌‌ی تلفن همراه : 'introduction/oem_news.md'

  - مفاهیم:
      - سخن آغازین : 'concepts/start_page.md'
      - انیمیشن راه‌اندازی: 'concepts/boot-animation.md'
      - امضای دیجیتالی: 'concepts/signing.md'
      - پارتیشن vendor : 'concepts/vendor_partition.md'


  -  فرآیند ساخت و نصب:
      - سخن آغازین : 'build/start_page.md'
      - فرآیند ساخت :     
          - پیش‌نیاز‌ها: 'build/requirement/index.md'
          - دریافت کد AOSP: 'build/aosp_code.md'
          - آشنایی با فرآیند ساخت: 'build/build.md'
          - فرآیند ساخت روی یک دستگاه : 'build/build-device.md'
          - امضای دیجیتالی فرآیند ساخت : 'build/build-signing.md'
          - اجرا روی شبیه‌ساز: 'build/emulator.md'   
          -  مشکلات فرآیند ساخت: 'build/problems/index.md'      
      - فرآیند نصب :
          -  انواع دستگاه‌ها : install/install.md
          - ملاحظات انواع دستگاه‌ها: install/intro.md
          - پشتیبان‌گیری و تغییر سیستم‌عامل: install/os-change.md
          - Tecno Camon C9: install/tecno/c9.md

  - نیازها و راه حل‌ها: 
      - سخن آغازین : 'needs_and_solutions/start_page.md'
      - تغییرات در فرآیند ساخت و نصب: 
          - قفل‌کردن دوباره‌ی bootloader : 'needs_and_solutions/before_making/relock_bootloader.md'
          - افزودن برنامه پیش‌فرض: 'needs_and_solutions/before_making/apk-bundling.md'
          - اضافه کردن نام دامنه : 'needs_and_solutions/before_making/set_host.md'
          - تغییر آدرس سرورهای dns : 'needs_and_solutions/before_making/change_dns.md'
      - تغییرات در سیسیتم‌عامل فعال: 
          - گلابی: 'needs_and_solutions/running_os/golabi.md'
      - مشکلات موجود: 
          - رمزنگاری صدا بر بستر شبکه‌ی موبایل : 'needs_and_solutions/current/voice_encryption.md'
          - پارتیشن vendor متناسب با s9: 'needs_and_solutions/current/s9_vendor_partition.md'

  - منابع:
    - معرفی منابع: 'references/index.md'
    - کتاب‌ها: 'references/books/books.md'
