site_name: 'راهنمای کامل توسعه هسته سیستم‌عامل اندروید'
site_description: 'همه چیز درباره کار با AOSP و برنامه‌نویسی و ایجاد تغییر در هسته سیستم‌عامل اندروید'
site_author: 'تیم سبا'
docs_dir: 'src'
site_dir: 'build/html'
extra_css:
  - assets/fastyle.css
theme:
  name: 'material'
  font: false
  language: 'fa'
  direction: 'rtl'
  logo:
    icon: 'smartphone'
  feature:
    tabs: true
nav:
  - راهنمای AOSP:
    - درباره این راهنما: 'index.md'
    - پروژه AOSP چیست؟: 'aosp/what-is-android-open-source-project.md'
    - نمای کلی کد منبع اندروید: 'aosp/aosp-code-modules-overview.md'
    - پروژه‌های مبتنی بر AOSP: aosp/aosp-based-projects.md

  - اخبار:
    - اخبار سیستم‌عامل: 'news/operating-system.md'
    - اخبار سازندگان گوشی: 'news/oem.md'

  - مفاهیم:
      - سخن آغازین : 'concepts/start_page.md'
      - انیمیشن راه‌اندازی: 'concepts/boot-animation.md'
      - امضای دیجیتال برنامک‌ها: 'concepts/app-signing.md'
      - پارتیشن‌ها در اندروید: 'concepts/android-disk-partitions.md'
      - پارتیشن vendor : 'concepts/partitions/vendor.md'
      - فرآیند به‌روزرسانی: concepts/ota-update-process.md
      - مودم: concepts/modem.md
      - پردازنده: concepts/processors.md




  - مقالات:
    - آیا اندروید متن‌باز است؟  : 'introduction/articles/is-android-open-source.md'
    - Google's iron grip on Android : 'introduction/articles/Google_iron_grip_on_Android.md'

  - فرآیند ساخت :
    - درباره فرآیند ساخت کد اندروید: 'build/index.md'
    - پیش‌نیاز‌ها: 'build/requirement/index.md'
    - دریافت کد AOSP: 'build/aosp_code.md'
    - آشنایی با فرآیند ساخت: 'build/build.md'
    - فرآیند ساخت روی یک دستگاه : 'build/build-device.md'
    - امضای دیجیتالی فرآیند ساخت : 'build/build-signing.md'
    - اجرا روی شبیه‌ساز: 'build/emulator.md'
    - مشکلات فرآیند ساخت: 'build/problems/index.md'

  - فرآیند نصب:
    - دستگاه‌های پشتیبانی شده: install/supported-devices.md
    - روش نصب انواع دستگاه‌ها: install/install.md
    - ملاحظات انواع دستگاه‌ها: install/intro.md
    - پشتیبان‌گیری و تغییر سیستم‌عامل: install/os-change.md
    - Tecno Camon C9: install/tecno/c9.md

  - نیازها و راه حل‌ها:
      - سخن آغازین : 'needs_and_solutions/start_page.md'
      - تغییرات در فرآیند ساخت و نصب:
          - قفل‌کردن دوباره‌ی bootloader : 'needs_and_solutions/before_making/relock_bootloader.md'
          - افزودن برنامه پیش‌فرض: 'needs_and_solutions/before_making/apk-bundling.md'
          - اضافه کردن نام دامنه : 'needs_and_solutions/before_making/set_host.md'
          - تغییر آدرس سرورهای dns : 'needs_and_solutions/before_making/change_dns.md'
          - افزودن کلید دیباگ ADB به سیستم‌عامل: 'needs_and_solutions/before_making/add-adb-vendor-key.md'
          - مجوزهای سیستمی : 'needs_and_solutions/before_making/systematic_access/systematic_access.md'
      - تغییرات در سیسیتم‌عامل فعال:
          - گلابی: 'needs_and_solutions/running_os/golabi.md'
      - مشکلات موجود:
          - رمزنگاری صدا بر بستر شبکه‌ی موبایل : 'needs_and_solutions/current/voice_encryption.md'
          - پارتیشن vendor متناسب با S9: 'needs_and_solutions/current/s9_vendor_partition.md'

  - سایر منابع:
    - معرفی منابع: 'references/index.md'
    - کتاب‌ها: 'references/books/books.md'
