site_name: 'راهنمای کامل توسعه هسته سیستم‌عامل اندروید'
site_description: 'همه چیز درباره کار با AOSP و برنامه‌نویسی و ایجاد تغییر در هسته سیستم‌عامل اندروید'
site_author: 'تیم سبا'
docs_dir: 'src'
site_dir: 'build/html'
extra_css:
  - assets/fastyle.css
theme:
  name: 'material'
  font: false
  language: 'fa'
  direction: 'rtl'
  logo:
    icon: 'smartphone'
  feature:
    tabs: true
nav:
  - آشنایی:
    - درباره راهنما: 'index.md'
    - AOSP چیست: 'introduction/aosp.md'
  - فرآیند ساخت:
    - پیش‌نیاز‌ها: 'build/requirement/index.md'
    - دریافت کد AOSP: 'build/aosp_code.md'
    - آشنایی با فرآیند ساخت: 'build/build.md'
    - اجرا روی شبیه‌ساز: 'build/emulator.md'
    - مشکلات: 'build/problems/index.md'

  - تغییرات ساده:
    - تغییرات ساده: 'modifications/index.md'
  - سایر منابع:
    - معرفی منابع: 'references/index.md'
    - کتاب‌ها: 'references/books.md'
