site_name: 'راهنمای کامل توسعه هسته سیستم‌عامل اندروید'
site_description: 'همه چیز درباره کار با AOSP و برنامه‌نویسی و ایجاد تغییر در هسته سیستم‌عامل اندروید'
site_author: 'تیم سبا'
docs_dir: 'src'
site_dir: 'build/html'
extra_css:
  - assets/fastyle.css
theme:
  name: 'material'
  font: false
  language: 'fa'
  direction: 'rtl'
  logo:
    icon: 'smartphone'
  feature:
    tabs: true
nav:
  - آشنایی:
    - آیا اندروید متن باز است؟: 'introduction/is-android-open-source.md'
    - AOSP چیست: 'introduction/aosp.md'
    - اصطلاحات اندروید: 'introduction/glossary.md'
    - درباره راهنما: 'index.md'

  - مفاهیم:
      - انیمیشن راه‌اندازی: 'concepts/boot-animation.md'
      - امضای دیجیتالی: 'concepts/signing.md'
      - پارتیشن vendor : 'concepts/vendor_partition.md'

  - فرآیند ساخت:
    - پیش‌نیاز‌ها: 'build/requirement/index.md'
    - دریافت کد AOSP: 'build/aosp_code.md'
    - آشنایی با فرآیند ساخت: 'build/build.md'
    - فرآیند ساخت روی یک دستگاه : 'build/build-device.md'
    - امضای دیجیتالی فرآیند ساخت : 'build/build-signing.md'
    - اجرا روی شبیه‌ساز: 'build/emulator.md'
    - مشکلات: 'build/problems/index.md'

  - فرآیند نصب:
    - نصب: install/install.md
    - ملاحظات انواع دستگاه‌ها: install/intro.md
    - پشتیبان‌گیری و تغییر سیستم‌عامل: install/os-change.md
    - Tecno Camon C9: install/tecno/c9.md

  - تغییرات ساده:
    - تغییرات ساده در سیستم‌عامل اندروید: 'modifications/index.md'
    - افزودن برنامه پیش‌فرض: 'modifications/apk-bundling.md'
    - اضافه کردن نام دامنه : 'modifications/set_host.md'
    - تغییر آدرس سرورهای dns : 'modifications/change_dns.md'

  - سایر منابع:
    - معرفی منابع: 'references/index.md'
    - کتاب‌ها: 'references/books.md'
